version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    target-branch: develop

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      pip:
        patterns:
          - "*"
    target-branch: develop

  - package-ecosystem: docker-compose
    directory: "/"
    schedule:
      interval: weekly
    groups:
      docker-compose:
        patterns:
          - "*"
    target-branch: develop
