x-default: &default
  restart: unless-stopped
  networks:
    - overlay

x-healthcheck-interval: &hc-interval
  interval: 30s
  timeout: 60s
  retries: 5
  start_period: 10s

x-api-environment: &api-environment
  ANALYZER_UVICORN_HOST: ${ANALYZER_UVICORN_HOST:-0.0.0.0}
  ANALYZER_UVICORN_PORT: ${ANALYZER_UVICORN_PORT:-8008}

services:
  nginx:
    <<: *default
    image: nginx:stable-alpine
    profiles: ["analyzer"]
    container_name: analyzer.nginx
    hostname: analyzer.nginx
    environment:
      <<: *api-environment
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/nginx/templates:/etc/nginx/templates
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_healthy

  api:
    <<: *default
    build:
      context: .
      dockerfile: ./deploy/analyzer/Dockerfile
    profiles: ["analyzer"]
    container_name: analyzer.api
    hostname: analyzer.api
    environment:
      <<: *api-environment
    command: just serve
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsSL http://localhost:${ANALYZER_UVICORN_PORT}/v1/healthcheck/",
        ]
      <<: *hc-interval

networks:
  overlay:
    driver: bridge
