name: Run all tests

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  pre-commit-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - uses: extractions/setup-just@v3

      - name: Install Dependencies and library
        run: uv pip install --system .[dev]

      - name: Load cached Pre-Commit Dependencies
        id: cached-pre-commit-dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Execute Pre-Commit
        run: just pre-commit
